package com.proyecto.vista;

//import com.mycompany.ilib.DAOUsersImpl;
//import com.mycompany.interfaces.DAOUsers;
import com.proyecto.controladores.ControladorRegistroCategoriaProducto;
import com.proyecto.controladores.ControladorRegistroCuentaBancaria;
import com.proyecto.controladores.ControladorRegistroProveedor;
import com.proyecto.controladores.ControladorRegistroUsuario;
import com.proyecto.entidades.CategoriaProducto;
import com.proyecto.entidades.CuentaBancaria;
import com.proyecto.entidades.Proveedor;
import com.proyecto.entidades.Usuario;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

public class VentanaRegistroCategoriaProducto extends javax.swing.JPanel {

    private ControladorRegistroCategoriaProducto controladorRegistroCategoriaProducto;
    boolean isEdition = false;
    private CategoriaProducto productCategoryEdition;

    public VentanaRegistroCategoriaProducto() {
        this.controladorRegistroCategoriaProducto = new ControladorRegistroCategoriaProducto();

        initComponents();
        InitStyles();

    }

    public VentanaRegistroCategoriaProducto(CategoriaProducto productCategory) {
        this.controladorRegistroCategoriaProducto = new ControladorRegistroCategoriaProducto();

        initComponents();
        isEdition = true;
        productCategoryEdition = productCategory;
        InitStyles();
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setForeground(Color.black);
        nombreCategoriaField.putClientProperty("JTextField.placeholderText", "Ingrese el nombre de la categoría.");
        descripcionCategoriaField.putClientProperty("JTextField.placeholderText", "Ingrese alguna descripción.");
        

        if (isEdition) {
            title.setText("EDITAR CATEGORIA DE PRODUCTO");
            registerButton.setText("Guardar");

            if (productCategoryEdition != null) {
                nombreCategoriaField.setText(productCategoryEdition.getNombreCategoria());
                descripcionCategoriaField.setText(productCategoryEdition.getDescripcionCategoria());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nombreCategoriaField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        descripcionCategoriaField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        registerButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("REGISTRAR NUEVA CATEGORIA DE PRODUCTO");

        nameLabel.setText("Nombre Categoría Producto");

        addressLabel.setText("Descripción");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        registerButton.setBackground(new java.awt.Color(255, 0, 51));
        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Registrar");
        registerButton.setBorderPainted(false);
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombreCategoriaField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(descripcionCategoriaField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(registerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreCategoriaField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(descripcionCategoriaField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed

        String nombreCategoria = nombreCategoriaField.getText();
        String descripcionCategoria = descripcionCategoriaField.getText();
        

        String successMsg = isEdition ? "modificado" : "registrado";
        String errorMsg = isEdition ? "modificar" : "registrar";

        // Validaciones para los campos
        if (nombreCategoria.isEmpty() || descripcionCategoria.isEmpty()) {
            
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            nombreCategoriaField.requestFocus();
            
        } else if (!isEdition) { // codigo donde se agrega
            
            try {
                //VALIDAR: El nombre de la nueva categoria no debe estar registrado en la base de datos.
                boolean nombreCategoriaEnUso = controladorRegistroCategoriaProducto.validarNombreCategoriaProductoEnUso(nombreCategoria);
                if(nombreCategoriaEnUso){
                    javax.swing.JOptionPane.showMessageDialog(this, "Al parecer el nombre de la categoria: " + nombreCategoria 
                            + " ya esta registrada.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                    nombreCategoriaField.requestFocus();
                    return;
                }
                
                boolean confirmarDatosCategoriaProducto = controladorRegistroCategoriaProducto.confirmarDatosCategoriaProducto(nombreCategoria, descripcionCategoria);
                if (confirmarDatosCategoriaProducto) {
                    controladorRegistroCategoriaProducto.registrarCategoriaProducto(nombreCategoria, descripcionCategoria);
                } else {
                    return;
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Categoría Producto " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " la categoría producto. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } else { // codigo donde se edita
            
            try {
                int idCategoria = productCategoryEdition.getIdCategoriaProducto();
                
                boolean confirmarDatosCategoriaProducto = controladorRegistroCategoriaProducto.confirmarDatosCategoriaProducto(nombreCategoria, descripcionCategoria);
                if (confirmarDatosCategoriaProducto) {
                    controladorRegistroCategoriaProducto.editarCategoriaProducto(idCategoria, nombreCategoria, descripcionCategoria);
                } else {
                    return;
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Proveedor " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el proveedor. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_registerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField descripcionCategoriaField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nombreCategoriaField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
