package com.proyecto.vista;

//import com.mycompany.ilib.DAOUsersImpl;
//import com.mycompany.interfaces.DAOUsers;
import com.proyecto.controladores.ControladorRegistroCuentaBancaria;
import com.proyecto.controladores.ControladorRegistroIngresoBancario;
import com.proyecto.controladores.ControladorRegistroProveedor;
import com.proyecto.controladores.ControladorRegistroUsuario;
import com.proyecto.entidades.CuentaBancaria;
import com.proyecto.entidades.Proveedor;
import com.proyecto.entidades.Usuario;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

public class VentanaRegistroIngresoBancario extends javax.swing.JPanel {

    private ControladorRegistroIngresoBancario controladorRegistroIngresoBancario;
    //boolean isEdition = false;
    private CuentaBancaria bankAccount;

    /*public VentanaRegistroIngresoBancario() {
        this.controladorRegistroCuentaBancaria = new ControladorRegistroCuentaBancaria();

        initComponents();
        InitStyles();

    }*/

    public VentanaRegistroIngresoBancario(CuentaBancaria bankAccount) {
        this.controladorRegistroIngresoBancario = new ControladorRegistroIngresoBancario();

        initComponents();
        //isEdition = true;
        this.bankAccount = bankAccount;
        InitStyles();
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setForeground(Color.black);
        montoIngresoField.putClientProperty("JTextField.placeholderText", "20,000");
        
        nombreCuentaField.setEditable(false);
        
        //saldoInicialField.putClientProperty("JTextField.placeholderText", "Ingrese teléfono del proveedor.");

        /*if (isEdition) {
            title.setText("Editar Proveedor");
            registerButton.setText("Guardar");

            if (supplierEdition != null) {
                nombreCuentaField.setText(supplierEdition.getNombre());
                tipoCuentaField.setText(supplierEdition.getDireccion());
                saldoInicialField.setText(supplierEdition.getTelefono());
                creditLineField.setText((String.valueOf(supplierEdition.getLineaCredito())));
            }
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nombreCuentaField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        montoIngresoField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        registerButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("REGISTRAR INGRESO BANCARIO");

        nameLabel.setText("Entidad Bancaria Selecionada");

        addressLabel.setText("Monto de ingreso: (max: 20,000)");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        registerButton.setBackground(new java.awt.Color(255, 0, 51));
        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Registrar ingreso");
        registerButton.setBorderPainted(false);
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nombreCuentaField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(registerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(montoIngresoField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreCuentaField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(montoIngresoField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(0, 82, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed

        String nombreCuenta = nombreCuentaField.getText();
        String montoIngreso = montoIngresoField.getText();
        

        //String successMsg = isEdition ? "modificado" : "registrado";
        //String errorMsg = isEdition ? "modificar" : "registrar";

        // Validaciones para los campos
        if (nombreCuenta.isEmpty() || montoIngreso.isEmpty()) {
            
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            montoIngresoField.requestFocus();
            
        } else { // codigo donde se agrega
            
            try {
                //VALIDAR: El monto de igreso no debe superar los 20000
                double montoIngresoDouble = Double.parseDouble(montoIngreso);
                if(montoIngresoDouble > 20000){
                    javax.swing.JOptionPane.showMessageDialog(this, "El monto ingresado no puede ser mayor a 20 000.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                    montoIngresoField.requestFocus();
                    return;
                }
                
                boolean confirmarDatosRegistroIngresoBancario = controladorRegistroIngresoBancario.confirmarDatosRegistroIngresoBancario(bankAccount, montoIngresoDouble);
                if (confirmarDatosRegistroIngresoBancario) {
                    controladorRegistroIngresoBancario.registrarIngresoBancario(bankAccount, montoIngresoDouble);
                } else {
                    return;
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Ingreso bancario registrado exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el ingreso bancario. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_registerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel bg;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField montoIngresoField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nombreCuentaField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
