package com.proyecto.vista;

//import com.mycompany.ilib.DAOUsersImpl;
//import com.mycompany.interfaces.DAOUsers;
import com.proyecto.controladores.ControladorDetalleExpedienteProveedor;
import com.proyecto.controladores.ControladorRegistroFactura;
import com.proyecto.controladores.ControladorRegistroProveedor;
import com.proyecto.controladores.ControladorRegistroUsuario;
import com.proyecto.entidades.Factura;
import com.proyecto.entidades.Producto;
import com.proyecto.entidades.Proveedor;
import com.proyecto.entidades.Usuario;
import static com.proyecto.utils.Utils.obtenerFechaActual;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VentanaDetalleExpedienteProveedor extends javax.swing.JPanel {

    private ControladorDetalleExpedienteProveedor controladorDetalleExpedienteProveedor;
    private Proveedor supplierShowing; 
    private Usuario currentUser;
    private DefaultTableModel modeloTabla;



    public VentanaDetalleExpedienteProveedor(Proveedor supplier, Usuario currentUser) throws Exception {
        this.controladorDetalleExpedienteProveedor = new ControladorDetalleExpedienteProveedor();
        this.modeloTabla = new DefaultTableModel();
        this.supplierShowing = supplier;
        this.currentUser = currentUser;

        initComponents();
        InitStyles();
        LoadProducts();
    }

    private void InitStyles() throws Exception {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setForeground(Color.black);

        nombreProveedorLabel.setText(supplierShowing.getNombre());
        direccionLabel.setText(supplierShowing.getDireccion());
        telefonoLabel1.setText(supplierShowing.getTelefono());
        lineaCreditoLabel.setText(Double.toString(supplierShowing.getLineaCredito()));
        
    }

    private void LoadProducts() {
        
        // Limpiar el modelo de la tabla
        modeloTabla.setRowCount(0);
        jTable1.setModel(modeloTabla);
        modeloTabla = controladorDetalleExpedienteProveedor.listarProductosProveedor(jTable1, supplierShowing.getIdProveedor());
        jTable1.setModel(modeloTabla);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nombreProveedorLabel = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        lineaCreditoLabel = new javax.swing.JLabel();
        nameLabel3 = new javax.swing.JLabel();
        telefonoLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        hitorialPagosBtn = new javax.swing.JButton();
        productosProveeBtn = new javax.swing.JButton();
        facturasPendientesBtn = new javax.swing.JButton();
        volvertBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("EXPEDIENTE PROVEEDOR");

        nameLabel.setText("Proveedor:");

        nombreProveedorLabel.setText("(nombre proveedor)");

        nameLabel1.setText("Dirección:");

        direccionLabel.setText("(direccion)");

        nameLabel2.setText("Telefono:");

        lineaCreditoLabel.setText("(lineaCredito)");

        nameLabel3.setText("Linea de Credito:");

        telefonoLabel1.setText("(telefono)");

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido P.", "Apellido M.", "Domicilio", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        hitorialPagosBtn.setBackground(new java.awt.Color(255, 0, 51));
        hitorialPagosBtn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        hitorialPagosBtn.setForeground(new java.awt.Color(255, 255, 255));
        hitorialPagosBtn.setText("Historial Pagos");
        hitorialPagosBtn.setBorderPainted(false);
        hitorialPagosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hitorialPagosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitorialPagosBtnActionPerformed(evt);
            }
        });

        productosProveeBtn.setBackground(new java.awt.Color(255, 0, 51));
        productosProveeBtn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        productosProveeBtn.setForeground(new java.awt.Color(255, 255, 255));
        productosProveeBtn.setText("Productos que Provee");
        productosProveeBtn.setBorderPainted(false);
        productosProveeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        productosProveeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosProveeBtnActionPerformed(evt);
            }
        });

        facturasPendientesBtn.setBackground(new java.awt.Color(255, 0, 51));
        facturasPendientesBtn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        facturasPendientesBtn.setForeground(new java.awt.Color(255, 255, 255));
        facturasPendientesBtn.setText("Facturas Pendientes");
        facturasPendientesBtn.setBorderPainted(false);
        facturasPendientesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        facturasPendientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturasPendientesBtnActionPerformed(evt);
            }
        });

        volvertBtn.setBackground(new java.awt.Color(255, 0, 51));
        volvertBtn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        volvertBtn.setForeground(new java.awt.Color(255, 255, 255));
        volvertBtn.setText("VOLVER");
        volvertBtn.setBorderPainted(false);
        volvertBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        volvertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volvertBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreProveedorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(direccionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(106, 106, 106)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(nameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lineaCreditoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(telefonoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(323, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(volvertBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(productosProveeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hitorialPagosBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facturasPendientesBtn))
                            .addComponent(jScrollPane1))
                        .addGap(31, 31, 31))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProveedorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineaCreditoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitorialPagosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productosProveeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facturasPendientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volvertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hitorialPagosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitorialPagosBtnActionPerformed

    }//GEN-LAST:event_hitorialPagosBtnActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

    }//GEN-LAST:event_jTable1MousePressed

    private void productosProveeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosProveeBtnActionPerformed
        // TODO add your handling code here:
        modeloTabla = controladorDetalleExpedienteProveedor.listarProductosProveedor(jTable1, supplierShowing.getIdProveedor());
        jTable1.setModel(modeloTabla);
    }//GEN-LAST:event_productosProveeBtnActionPerformed

    private void facturasPendientesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturasPendientesBtnActionPerformed
        // TODO add your handling code here:
        modeloTabla = controladorDetalleExpedienteProveedor.listarFacturasPendientesProveedor(jTable1, supplierShowing.getIdProveedor());
        jTable1.setModel(modeloTabla);
    }//GEN-LAST:event_facturasPendientesBtnActionPerformed

    private void volvertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volvertBtnActionPerformed
        // TODO add your handling code here:
        VentanaDashboard.ShowJPanelWindows(new VentanaGestorExpedienteProveedores(currentUser));
    }//GEN-LAST:event_volvertBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JButton facturasPendientesBtn;
    private javax.swing.JButton hitorialPagosBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lineaCreditoLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JLabel nombreProveedorLabel;
    private javax.swing.JButton productosProveeBtn;
    private javax.swing.JLabel telefonoLabel1;
    private javax.swing.JLabel title;
    private javax.swing.JButton volvertBtn;
    // End of variables declaration//GEN-END:variables
}
