/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyecto.vista;

import com.proyecto.entidades.Usuario;
import static com.proyecto.utils.Utils.reiniciarPrograma;

/**
 *
 * @author skivaS
 */
public class VentanaMenuAlmacenero extends javax.swing.JPanel {
    
    private VentanaDashboard ventanaDashboard;
    private Usuario currentUser;

    /**
     * Creates new form VentanaMenuAdministrador
     */
    public VentanaMenuAlmacenero(Usuario currentUser) {
        this.currentUser = currentUser;
        initComponents();
    }

    public void cerrarVentanaDashboard() {
        if (ventanaDashboard != null) {
            ventanaDashboard.cerrarVentana();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalBtn = new javax.swing.JButton();
        cerrarSesionBtn = new javax.swing.JButton();
        gestionarInventarioBtn = new javax.swing.JButton();
        gentionarFacturasBtn = new javax.swing.JButton();
        gestionarCategoriasBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 0, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        principalBtn.setBackground(new java.awt.Color(255, 0, 51));
        principalBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        principalBtn.setForeground(new java.awt.Color(255, 255, 255));
        principalBtn.setText("Principal");
        principalBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        principalBtn.setBorderPainted(false);
        principalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        principalBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        principalBtn.setIconTextGap(13);
        principalBtn.setInheritsPopupMenu(true);
        principalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalBtnActionPerformed(evt);
            }
        });
        add(principalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 60));

        cerrarSesionBtn.setBackground(new java.awt.Color(255, 0, 51));
        cerrarSesionBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cerrarSesionBtn.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesionBtn.setText("Cerrar Sesion");
        cerrarSesionBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        cerrarSesionBtn.setBorderPainted(false);
        cerrarSesionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrarSesionBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cerrarSesionBtn.setIconTextGap(13);
        cerrarSesionBtn.setInheritsPopupMenu(true);
        cerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBtnActionPerformed(evt);
            }
        });
        add(cerrarSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 60));

        gestionarInventarioBtn.setBackground(new java.awt.Color(255, 0, 51));
        gestionarInventarioBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gestionarInventarioBtn.setForeground(new java.awt.Color(255, 255, 255));
        gestionarInventarioBtn.setText("Gestionar Inventario");
        gestionarInventarioBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        gestionarInventarioBtn.setBorderPainted(false);
        gestionarInventarioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gestionarInventarioBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gestionarInventarioBtn.setIconTextGap(13);
        gestionarInventarioBtn.setInheritsPopupMenu(true);
        gestionarInventarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarInventarioBtnActionPerformed(evt);
            }
        });
        add(gestionarInventarioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 270, 60));

        gentionarFacturasBtn.setBackground(new java.awt.Color(255, 0, 51));
        gentionarFacturasBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gentionarFacturasBtn.setForeground(new java.awt.Color(255, 255, 255));
        gentionarFacturasBtn.setText("Actualizar informacion Productos");
        gentionarFacturasBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        gentionarFacturasBtn.setBorderPainted(false);
        gentionarFacturasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gentionarFacturasBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gentionarFacturasBtn.setIconTextGap(13);
        gentionarFacturasBtn.setInheritsPopupMenu(true);
        gentionarFacturasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gentionarFacturasBtnActionPerformed(evt);
            }
        });
        add(gentionarFacturasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 270, 60));

        gestionarCategoriasBtn.setBackground(new java.awt.Color(255, 0, 51));
        gestionarCategoriasBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gestionarCategoriasBtn.setForeground(new java.awt.Color(255, 255, 255));
        gestionarCategoriasBtn.setText("Gestionar Categoría Productos");
        gestionarCategoriasBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        gestionarCategoriasBtn.setBorderPainted(false);
        gestionarCategoriasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gestionarCategoriasBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gestionarCategoriasBtn.setIconTextGap(13);
        gestionarCategoriasBtn.setInheritsPopupMenu(true);
        gestionarCategoriasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarCategoriasBtnActionPerformed(evt);
            }
        });
        add(gestionarCategoriasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void principalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalBtnActionPerformed
        VentanaDashboard.ShowJPanelWindows(new VentanaPrincipal(currentUser));
    }//GEN-LAST:event_principalBtnActionPerformed

    private void cerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBtnActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        
        reiniciarPrograma();
    }//GEN-LAST:event_cerrarSesionBtnActionPerformed

    private void gestionarInventarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarInventarioBtnActionPerformed
        // TODO add your handling code here:
        VentanaDashboard.ShowJPanelWindows(new VentanaGestorInventario(currentUser));
    }//GEN-LAST:event_gestionarInventarioBtnActionPerformed

    private void gentionarFacturasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gentionarFacturasBtnActionPerformed
        // TODO add your handling code here:
        //VentanaDashboard.ShowJPanelWindows(new VentanaGestorFacturas(currentUser));
    }//GEN-LAST:event_gentionarFacturasBtnActionPerformed

    private void gestionarCategoriasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarCategoriasBtnActionPerformed
        // TODO add your handling code here:
        VentanaDashboard.ShowJPanelWindows(new VentanaGestorCategoriasProducto(currentUser));
    }//GEN-LAST:event_gestionarCategoriasBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarSesionBtn;
    private javax.swing.JButton gentionarFacturasBtn;
    private javax.swing.JButton gestionarCategoriasBtn;
    private javax.swing.JButton gestionarInventarioBtn;
    private javax.swing.JButton principalBtn;
    // End of variables declaration//GEN-END:variables
}
