/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyecto.vista;

import com.proyecto.entidades.Usuario;
import static com.proyecto.utils.Utils.reiniciarPrograma;

/**
 *
 * @author skiva
 */
public class VentanaMenuJefeFinanzas extends javax.swing.JPanel {
    
    private VentanaDashboard ventanaDashboard;
    private Usuario currentUser;

    /**
     * Creates new form VentanaMenuAdministrador
     */
    public VentanaMenuJefeFinanzas(Usuario currentUser) {
        this.currentUser = currentUser;
        initComponents();
    }

    public void cerrarVentanaDashboard() {
        if (ventanaDashboard != null) {
            ventanaDashboard.cerrarVentana();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalBtn = new javax.swing.JButton();
        cerrarSesionBtn = new javax.swing.JButton();
        aprobarRechazarBtn = new javax.swing.JButton();
        gentionarFacturasBtn = new javax.swing.JButton();
        gestionarCuentasBancarias = new javax.swing.JButton();
        gentionarFacturasBtn2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 0, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        principalBtn.setBackground(new java.awt.Color(255, 0, 51));
        principalBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        principalBtn.setForeground(new java.awt.Color(255, 255, 255));
        principalBtn.setText("Principal");
        principalBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        principalBtn.setBorderPainted(false);
        principalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        principalBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        principalBtn.setIconTextGap(13);
        principalBtn.setInheritsPopupMenu(true);
        principalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalBtnActionPerformed(evt);
            }
        });
        add(principalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 60));

        cerrarSesionBtn.setBackground(new java.awt.Color(255, 0, 51));
        cerrarSesionBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cerrarSesionBtn.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesionBtn.setText("Cerrar Sesion");
        cerrarSesionBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        cerrarSesionBtn.setBorderPainted(false);
        cerrarSesionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrarSesionBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cerrarSesionBtn.setIconTextGap(13);
        cerrarSesionBtn.setInheritsPopupMenu(true);
        cerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBtnActionPerformed(evt);
            }
        });
        add(cerrarSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 270, 60));

        aprobarRechazarBtn.setBackground(new java.awt.Color(255, 0, 51));
        aprobarRechazarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aprobarRechazarBtn.setForeground(new java.awt.Color(255, 255, 255));
        aprobarRechazarBtn.setText("Aprobar o Rechazar Pago");
        aprobarRechazarBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        aprobarRechazarBtn.setBorderPainted(false);
        aprobarRechazarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aprobarRechazarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aprobarRechazarBtn.setIconTextGap(13);
        aprobarRechazarBtn.setInheritsPopupMenu(true);
        aprobarRechazarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprobarRechazarBtnActionPerformed(evt);
            }
        });
        add(aprobarRechazarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 270, 60));

        gentionarFacturasBtn.setBackground(new java.awt.Color(255, 0, 51));
        gentionarFacturasBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gentionarFacturasBtn.setForeground(new java.awt.Color(255, 255, 255));
        gentionarFacturasBtn.setText("Registrar egreso bancos");
        gentionarFacturasBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        gentionarFacturasBtn.setBorderPainted(false);
        gentionarFacturasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gentionarFacturasBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gentionarFacturasBtn.setIconTextGap(13);
        gentionarFacturasBtn.setInheritsPopupMenu(true);
        gentionarFacturasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gentionarFacturasBtnActionPerformed(evt);
            }
        });
        add(gentionarFacturasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 60));

        gestionarCuentasBancarias.setBackground(new java.awt.Color(255, 0, 51));
        gestionarCuentasBancarias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gestionarCuentasBancarias.setForeground(new java.awt.Color(255, 255, 255));
        gestionarCuentasBancarias.setText("Gestionar cuentas bancarias");
        gestionarCuentasBancarias.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        gestionarCuentasBancarias.setBorderPainted(false);
        gestionarCuentasBancarias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gestionarCuentasBancarias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gestionarCuentasBancarias.setIconTextGap(13);
        gestionarCuentasBancarias.setInheritsPopupMenu(true);
        gestionarCuentasBancarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarCuentasBancariasActionPerformed(evt);
            }
        });
        add(gestionarCuentasBancarias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 60));

        gentionarFacturasBtn2.setBackground(new java.awt.Color(255, 0, 51));
        gentionarFacturasBtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gentionarFacturasBtn2.setForeground(new java.awt.Color(255, 255, 255));
        gentionarFacturasBtn2.setText("Registrar ingreso bancos");
        gentionarFacturasBtn2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        gentionarFacturasBtn2.setBorderPainted(false);
        gentionarFacturasBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gentionarFacturasBtn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gentionarFacturasBtn2.setIconTextGap(13);
        gentionarFacturasBtn2.setInheritsPopupMenu(true);
        gentionarFacturasBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gentionarFacturasBtn2ActionPerformed(evt);
            }
        });
        add(gentionarFacturasBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 270, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void principalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalBtnActionPerformed
        VentanaDashboard.ShowJPanelWindows(new VentanaPrincipal(currentUser));
    }//GEN-LAST:event_principalBtnActionPerformed

    private void cerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBtnActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        
        reiniciarPrograma();
    }//GEN-LAST:event_cerrarSesionBtnActionPerformed

    private void aprobarRechazarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprobarRechazarBtnActionPerformed
        // TODO add your handling code here:
        VentanaDashboard.ShowJPanelWindows(new VentanaGestorSolicitudesPago(currentUser));
    }//GEN-LAST:event_aprobarRechazarBtnActionPerformed

    private void gentionarFacturasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gentionarFacturasBtnActionPerformed
        // TODO add your handling code here:
        //VentanaDashboard.ShowJPanelWindows(new VentanaGestorFacturas(currentUser));
    }//GEN-LAST:event_gentionarFacturasBtnActionPerformed

    private void gestionarCuentasBancariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarCuentasBancariasActionPerformed
        // TODO add your handling code here:
        VentanaDashboard.ShowJPanelWindows(new VentanaGestorCuentasBancarias(currentUser));
    }//GEN-LAST:event_gestionarCuentasBancariasActionPerformed

    private void gentionarFacturasBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gentionarFacturasBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gentionarFacturasBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aprobarRechazarBtn;
    private javax.swing.JButton cerrarSesionBtn;
    private javax.swing.JButton gentionarFacturasBtn;
    private javax.swing.JButton gentionarFacturasBtn2;
    private javax.swing.JButton gestionarCuentasBancarias;
    private javax.swing.JButton principalBtn;
    // End of variables declaration//GEN-END:variables
}
