package com.proyecto.vista;

//import com.mycompany.ilib.DAOUsersImpl;
//import com.mycompany.interfaces.DAOUsers;
import com.proyecto.controladores.ControladorDetalleExpedienteProveedor;
import com.proyecto.controladores.ControladorRegistroFactura;
import com.proyecto.controladores.ControladorRegistroProveedor;
import com.proyecto.controladores.ControladorRegistroUsuario;
import com.proyecto.entidades.Factura;
import com.proyecto.entidades.Producto;
import com.proyecto.entidades.Proveedor;
import com.proyecto.entidades.Usuario;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class VentanaDetalleExpedienteProveedor extends javax.swing.JPanel {

    private ControladorDetalleExpedienteProveedor controladorDetalleExpedienteProveedor;
    private Proveedor supplierShowing; 
    private Usuario currentUser;
    private DefaultTableModel modeloTabla;



    public VentanaDetalleExpedienteProveedor(Proveedor supplier, Usuario currentUser) throws Exception {
        this.controladorDetalleExpedienteProveedor = new ControladorDetalleExpedienteProveedor();
        this.modeloTabla = new DefaultTableModel();
        this.supplierShowing = supplier;
        this.currentUser = currentUser;

        initComponents();
        InitStyles();
        LoadProducts();
    }

    private void InitStyles() throws Exception {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setForeground(Color.black);

        nombreProveedorField.setText(supplierShowing.getNombre());
        nombreProveedorField.setEditable(false);
        direccionField.setText(supplierShowing.getDireccion());
        direccionField.setEditable(false);
        telefonoField.setText(supplierShowing.getTelefono());
        telefonoField.setEditable(false);
        lineaCreditoField.setText(Double.toString(supplierShowing.getLineaCredito()));
        lineaCreditoField.setEditable(false);
        
    }

    private void LoadProducts() {
        
        // Limpiar el modelo de la tabla
        modeloTabla.setRowCount(0);
        expedienteProveedorTable.setModel(modeloTabla);
        modeloTabla = controladorDetalleExpedienteProveedor.listarProductosProveedor(expedienteProveedorTable, supplierShowing.getIdProveedor());
        expedienteProveedorTable.setModel(modeloTabla);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        expedienteProveedorTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nombreProveedorField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        direccionField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        telefonoField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lineaCreditoField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        mostrarProductosBtn = new javax.swing.JButton();
        facturasPendientesBtn = new javax.swing.JButton();
        historialTransaccionesBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("DETALLES DE PROVEEDOR");

        expedienteProveedorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(expedienteProveedorTable);

        jLabel10.setText("PROVEEDOR");

        jLabel11.setText("Nombre:");

        jLabel12.setText("Dirección:");

        jLabel13.setText("Telefono:");

        jLabel14.setText("Linea de credito:");

        mostrarProductosBtn.setBackground(new java.awt.Color(255, 0, 51));
        mostrarProductosBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mostrarProductosBtn.setForeground(new java.awt.Color(255, 255, 255));
        mostrarProductosBtn.setText("PRODUCTOS");
        mostrarProductosBtn.setBorderPainted(false);
        mostrarProductosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mostrarProductosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarProductosBtnActionPerformed(evt);
            }
        });

        facturasPendientesBtn.setBackground(new java.awt.Color(255, 0, 51));
        facturasPendientesBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        facturasPendientesBtn.setForeground(new java.awt.Color(255, 255, 255));
        facturasPendientesBtn.setText("FACTURAS PENDIENTES");
        facturasPendientesBtn.setBorderPainted(false);
        facturasPendientesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        facturasPendientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturasPendientesBtnActionPerformed(evt);
            }
        });

        historialTransaccionesBtn.setBackground(new java.awt.Color(255, 0, 51));
        historialTransaccionesBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        historialTransaccionesBtn.setForeground(new java.awt.Color(255, 255, 255));
        historialTransaccionesBtn.setText("HISTORIAL TRANSACCIONES");
        historialTransaccionesBtn.setBorderPainted(false);
        historialTransaccionesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        historialTransaccionesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialTransaccionesBtnActionPerformed(evt);
            }
        });

        volverBtn.setBackground(new java.awt.Color(255, 0, 51));
        volverBtn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("VOLVER");
        volverBtn.setBorderPainted(false);
        volverBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(mostrarProductosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(facturasPendientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(historialTransaccionesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(volverBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nombreProveedorField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(direccionField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lineaCreditoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nombreProveedorField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(direccionField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(lineaCreditoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrarProductosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facturasPendientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historialTransaccionesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarProductosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarProductosBtnActionPerformed
        // TODO add your handling code here:
        modeloTabla = controladorDetalleExpedienteProveedor.listarProductosProveedor(expedienteProveedorTable, supplierShowing.getIdProveedor());
        expedienteProveedorTable.setModel(modeloTabla);
    }//GEN-LAST:event_mostrarProductosBtnActionPerformed

    private void facturasPendientesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturasPendientesBtnActionPerformed
        // TODO add your handling code here:
        modeloTabla = controladorDetalleExpedienteProveedor.listarFacturasPendientesProveedor(expedienteProveedorTable, supplierShowing.getIdProveedor());
        expedienteProveedorTable.setModel(modeloTabla);
    }//GEN-LAST:event_facturasPendientesBtnActionPerformed

    private void historialTransaccionesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialTransaccionesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historialTransaccionesBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
        VentanaDashboard.ShowJPanelWindows(new VentanaGestorExpedienteProveedores(currentUser));
    }//GEN-LAST:event_volverBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JTextField direccionField;
    private javax.swing.JTable expedienteProveedorTable;
    private javax.swing.JButton facturasPendientesBtn;
    private javax.swing.JButton historialTransaccionesBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lineaCreditoField;
    private javax.swing.JButton mostrarProductosBtn;
    private javax.swing.JTextField nombreProveedorField;
    private javax.swing.JTextField telefonoField;
    private javax.swing.JLabel title;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
