package com.proyecto.vista;

//import com.mycompany.ilib.DAOUsersImpl;
//import com.proyecto.vista.VentanaDashboard;
//import com.mycompany.interfaces.DAOUsers;
import com.proyecto.controladores.ControladorGestorEstadoCuentas;
import com.proyecto.controladores.ControladorGestorProveedores;
import com.proyecto.controladores.ControladorGestorUsuarios;
import com.proyecto.entidades.Usuario;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class VentanaGestorEstadoCuentas extends javax.swing.JPanel {

    private Usuario currentUser;
    private ControladorGestorEstadoCuentas controladorGestorEstadoCuentas;
    private DefaultTableModel modeloTabla;

    public VentanaGestorEstadoCuentas(Usuario currentUser) {
        this.controladorGestorEstadoCuentas = new ControladorGestorEstadoCuentas();
        this.currentUser = currentUser;
        this.modeloTabla = new DefaultTableModel();

        initComponents();
        InitStyles();
        LoadInvoices();
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setForeground(Color.black);
        userSearchField.putClientProperty("JTextField.placeholderText", "Ingrese el nombre de usuario a buscar.");
    }

    private void LoadInvoices() {
        
        // Limpiar el modelo de la tabla
        modeloTabla.setRowCount(0);
        jTable1.setModel(modeloTabla);

        modeloTabla = controladorGestorEstadoCuentas.listarFacturas(jTable1);
        jTable1.setModel(modeloTabla);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        facturasPendientesBtn = new javax.swing.JButton();
        filtro30Btn = new javax.swing.JButton();
        filtro60Btn = new javax.swing.JButton();
        filtro90Btn = new javax.swing.JButton();
        facturasPagadasBtn = new javax.swing.JButton();
        bancosBtn = new javax.swing.JButton();
        userSearchField = new javax.swing.JTextField();
        filtroTodosBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("ESTADOS DE CUENTAS");

        searchButton.setBackground(new java.awt.Color(255, 0, 51));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Buscar");
        searchButton.setBorderPainted(false);
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDFactura", "Proveedor", "Fecha Registro", "Fecha Vencimiento", "Descripción", "Monto Total", "Monto Pagado", "Monto Pendiente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        facturasPendientesBtn.setBackground(new java.awt.Color(255, 0, 51));
        facturasPendientesBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        facturasPendientesBtn.setForeground(new java.awt.Color(255, 255, 255));
        facturasPendientesBtn.setText("Facturas Pendientes");
        facturasPendientesBtn.setBorderPainted(false);
        facturasPendientesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        facturasPendientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturasPendientesBtnActionPerformed(evt);
            }
        });

        filtro30Btn.setBackground(new java.awt.Color(255, 0, 51));
        filtro30Btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        filtro30Btn.setForeground(new java.awt.Color(255, 255, 255));
        filtro30Btn.setText("30");
        filtro30Btn.setBorderPainted(false);
        filtro30Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        filtro30Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtro30BtnActionPerformed(evt);
            }
        });

        filtro60Btn.setBackground(new java.awt.Color(255, 0, 51));
        filtro60Btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        filtro60Btn.setForeground(new java.awt.Color(255, 255, 255));
        filtro60Btn.setText("60");
        filtro60Btn.setBorderPainted(false);
        filtro60Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        filtro60Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtro60BtnActionPerformed(evt);
            }
        });

        filtro90Btn.setBackground(new java.awt.Color(255, 0, 51));
        filtro90Btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        filtro90Btn.setForeground(new java.awt.Color(255, 255, 255));
        filtro90Btn.setText("90");
        filtro90Btn.setBorderPainted(false);
        filtro90Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        filtro90Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtro90BtnActionPerformed(evt);
            }
        });

        facturasPagadasBtn.setBackground(new java.awt.Color(255, 0, 51));
        facturasPagadasBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        facturasPagadasBtn.setForeground(new java.awt.Color(255, 255, 255));
        facturasPagadasBtn.setText("Facturas Pagadas");
        facturasPagadasBtn.setBorderPainted(false);
        facturasPagadasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        facturasPagadasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturasPagadasBtnActionPerformed(evt);
            }
        });

        bancosBtn.setBackground(new java.awt.Color(255, 0, 51));
        bancosBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bancosBtn.setForeground(new java.awt.Color(255, 255, 255));
        bancosBtn.setText("Bancos");
        bancosBtn.setBorderPainted(false);
        bancosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bancosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bancosBtnActionPerformed(evt);
            }
        });

        filtroTodosBtn.setBackground(new java.awt.Color(255, 0, 51));
        filtroTodosBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        filtroTodosBtn.setForeground(new java.awt.Color(255, 255, 255));
        filtroTodosBtn.setText("Todos");
        filtroTodosBtn.setBorderPainted(false);
        filtroTodosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        filtroTodosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroTodosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bancosBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(facturasPendientesBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(facturasPagadasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(userSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filtro30Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filtro60Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filtro90Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filtroTodosBtn)))
                        .addGap(34, 34, 34))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userSearchField)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filtro30Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filtro60Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filtro90Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filtroTodosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facturasPendientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facturasPagadasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bancosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

    }//GEN-LAST:event_jTable1MousePressed

    private void facturasPendientesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturasPendientesBtnActionPerformed
        modeloTabla = controladorGestorEstadoCuentas.filtrarFacturasPendientes(jTable1);
        jTable1.setModel(modeloTabla);
    }//GEN-LAST:event_facturasPendientesBtnActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        
        modeloTabla = controladorGestorEstadoCuentas.buscarFacturas(jTable1, userSearchField.getText());
        jTable1.setModel(modeloTabla);


    }//GEN-LAST:event_searchButtonActionPerformed

    private void filtro30BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtro30BtnActionPerformed
        // TODO add your handling code here:
        modeloTabla = controladorGestorEstadoCuentas.filtrarPor30Dias(jTable1);
        jTable1.setModel(modeloTabla);
    }//GEN-LAST:event_filtro30BtnActionPerformed

    private void filtro60BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtro60BtnActionPerformed
        // TODO add your handling code here:
        modeloTabla = controladorGestorEstadoCuentas.filtrarPor60Dias(jTable1);
        jTable1.setModel(modeloTabla);
    }//GEN-LAST:event_filtro60BtnActionPerformed

    private void filtro90BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtro90BtnActionPerformed
        // TODO add your handling code here:
        modeloTabla = controladorGestorEstadoCuentas.filtrarPor90Dias(jTable1);
        jTable1.setModel(modeloTabla);
    }//GEN-LAST:event_filtro90BtnActionPerformed

    private void facturasPagadasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturasPagadasBtnActionPerformed
        // TODO add your handling code here:
        modeloTabla = controladorGestorEstadoCuentas.filtrarFacturasPagadas(jTable1);
        jTable1.setModel(modeloTabla);
    }//GEN-LAST:event_facturasPagadasBtnActionPerformed

    private void bancosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bancosBtnActionPerformed
        try {
            VentanaDashboard.ShowJPanelWindows(new VentanaDetalleBancos(currentUser));
        } catch (Exception ex) {
            Logger.getLogger(VentanaGestorEstadoCuentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bancosBtnActionPerformed

    private void filtroTodosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroTodosBtnActionPerformed
        // TODO add your handling code here:
        modeloTabla = controladorGestorEstadoCuentas.filtrarTodasFacturas(jTable1);
        jTable1.setModel(modeloTabla);
    }//GEN-LAST:event_filtroTodosBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bancosBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JButton facturasPagadasBtn;
    private javax.swing.JButton facturasPendientesBtn;
    private javax.swing.JButton filtro30Btn;
    private javax.swing.JButton filtro60Btn;
    private javax.swing.JButton filtro90Btn;
    private javax.swing.JButton filtroTodosBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel title;
    private javax.swing.JTextField userSearchField;
    // End of variables declaration//GEN-END:variables
}
